import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
// const inter = Kumbh_Sans({
//   subsets: ["latin", "latin-ext"],
//   weight: ["200", "300", "400", "500"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>{children}</body>
      <Toaster />
    </html>
  );
}
